name: flutter_geoloc3
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  location: ^7.0.1
  permission_handler: ^11.3.1
  background_task: ^0.2.0+2
  intl: ^0.19.0
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  isar: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.3
  isar_flutter_libs: ^3.1.0+1

  google_fonts: ^6.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true
